config/routes.rb
Rails.application.routes.draw do
  resources :user_requests
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'news#index'
  namespace :admin do
    resources :news
    resources :docs
    resources :user_requests
    resources :users
  end
  resources :news, only: [:index]
  resources :info, only: [:index]
  resources :docs, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  has_attached_file :document,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join('config/dropbox.yml')

  validates_attachment_content_type :document, content_type: [/pdf\Z/]
end

app/models/new.rb
class New < ApplicationRecord
  validates :title, :description,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_requests
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
end

app/models/user_request.rb
class UserRequest < ApplicationRecord
  belongs_to :user
  after_create :send_notification
  private
  def send_notification
    UserRequestMailer.user_request(self.user.email,self.text).deliver_now
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'admin/application'
  before_action :authenticate_user!
  before_action :auth_admin!
  private
   def auth_admin!
      redirect_to news_index_path unless user_signed_in? and current_user.admin 
   end
end

app/controllers/admin/docs_controller.rb
class Admin::DocsController < Admin::ApplicationController
  before_action :doc_find, only: [:edit, :update, :destroy]
  def index
    @docs=Doc.all
  end
  def new
    @doc=Doc.new
  end
  def create
    Doc.create(doc_params)
    redirect_to admin_docs_path
  end
  def edit
  end
  def update
    @doc.update(doc_params)
    redirect_to admin_docs_path
  end
  def destroy
    @doc.destroy
    redirect_to admin_docs_path
  end
  private
  def doc_params
    params.require(:doc).permit(:title, :document)
  end
  def doc_find
    @doc=Doc.find(params[:id])
  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::ApplicationController
  before_action :new_find, only: [:edit, :update, :destroy]
  def index
    @news=New.all.order(created_at: :desc)
  end
  def edit 
  end
  def update 
    if @new.update(new_params)
      redirect_to admin_news_index_path
    else
      render :edit
    end
  end
  def new
    @new= New.new
  end
  def create
   @new= New.new(new_params)
   if @new.save
      redirect_to admin_news_index_path
   else
     render :new
   end
  end
  def destroy
    @new.destroy
    redirect_to admin_news_index_path
  end
   private
   def new_params
     params.require(:new).permit(:title, :description, :date)
   end
   def new_find
    @new=New.find(params[:id])
   end
end

app/controllers/admin/user_requests_controller.rb
class Admin::UserRequestsController < Admin::ApplicationController
  def index
    @user_requests=UserRequest.all
  end
  def show
  end
  def destroy
    @user_request=UserRequest.find(params[:id])
    @user_request.destroy
    redirect_to  admin_user_requests_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users=User.all
  end
  def destroy
    @user=User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def index
    @docs=Doc.all
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end

end

app/controllers/news_controller.rb
class NewsController<ApplicationController
  def index
    @news=New.all.order(created_at: :desc)
  end
end

app/controllers/user_requests_controller.rb
class UserRequestsController < ApplicationController
  before_action :authenticate_user!
  def new
    @user_request=UserRequest.new
  end
  def create
    @user_request=UserRequest.new(user_request_params)
    @user_request.user=current_user
    @user_request.save
    redirect_to news_index_path
  end
  private
  def user_request_params
    params.require(:user_request).permit(:text)
  end
end

app/helpers/admin/user_requests_helper.rb
module Admin::UserRequestsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/user_requests_helper.rb
module UserRequestsHelper
end

app/views/admin/docs/edit.html.haml
.container
  .row
    .col-md-6
      .panel.panel-success
        .panel-heading
          Редактируем документ 
        .panel-body
          = simple_form_for @doc, url: {action: 'update'}, html: { multipart: true } do |f|
            = f.input :title, label: 'Название документа'
            = f.input :document, as: :file, label: 'Загрузить pdf'
            = f.button :submit, 'Обновить'

app/views/admin/docs/index.html.haml
.panel.panel-default
  %table.table
    %tr.info
      %td Документ
      %td Имя файла
      %td Размер
      %td Создан
      %td Изменен
      %td
    - @docs.each do |doc|
      %tr
        %td 
          = doc.title
        %td
          = doc.document_file_name
        %td
          = doc.document_file_size
        %td 
          = doc.created_at
        %td
          = doc.updated_at
        %td
          .text-right
            = link_to content_tag('span','',class: 'glyphicon glyphicon-search'), doc.document.url
            = link_to content_tag('span','', class: 'glyphicon glyphicon-pencil'), edit_admin_doc_path(doc)
            = link_to content_tag('span','', class: 'glyphicon glyphicon-remove'),doc, method: :delete, data: {confirm: 'Ты уверен ?'} 
=link_to 'Создать документ',new_admin_doc_path 

app/views/admin/docs/new.html.haml
.container
  .row
    .col-md-6
      .panel.panel-success
        .panel-heading
          Создаем документ 
        .panel-body
          = simple_form_for @doc, url: {controller: 'admin/docs', action: 'create'}, html: { multipart: true } do |f|
            = f.input :title, label: 'Название'
            = f.input :document, as: :file, label: 'Загружаем pdf'
            = f.button :submit, 'Сохраняем'

app/views/admin/news/edit.html.haml
.container
  .row
    .col-md-6
      .panel.panel-success
        .panel-heading
          Редактируем сообщение
        .panel-body
          = simple_form_for @new, url: {action: 'update'} do |f| 
            = f.input :title, label: 'Заголовок' 
            = f.input :description, as: :text
            = f.input :date, label: 'Дата'
            = f.button :submit, 'Обновить'

app/views/admin/news/index.html.haml
.panel.panel-default
  %table.table 
    %tr.info
      %td Заголовок
      %td Сообщение
      %td Дата
      %td Создано
      %td Изменено
      %td
    - @news.each do |new| 
      %tr
        %td
          = new.title
        %td 
          = new.description
        %td 
          = new.date
        %td
          = new.created_at
        %td
          = new.updated_at
        %td 
          = link_to content_tag('span','',class: 'glyphicon glyphicon-pencil'), edit_admin_news_path(new) 
          = link_to content_tag('span','',class: 'glyphicon glyphicon-remove'),admin_news_path(new), method: :delete, data: { confirm: 'Ты уверен ?' } 

= link_to 'Добавить запись', new_admin_news_path

app/views/admin/news/new.html.haml
.container
  .row
    .col-md-6
      .panel.panel-success
        .panel-heading
          Создаем собщение... 
        .panel-body
          = simple_form_for @new, url: {action: 'create'} do |f| 
            = f.input :title, label: 'Заголовок' 
            = f.input :description, as: :text, label: 'Сообщение'
            = f.input :date, label: 'Дата'
            = f.button :submit,'Создать'

app/views/admin/user_requests/index.html.haml
.panel.panel-default
  %table.table 
    %tr.info
      %td Дата
      %td Пользователь
      %td Сообщение
      %td  
        - @user_requests.each do |user_request|
          %tr
            %td 
              =user_request.created_at
            %td 
              =user_request.user.email
            %td 
              =user_request.text
            %td 
              = link_to 'Удалить', admin_user_request_path(user_request), method: :delete, data: {confirm: 'Ты уверен ?'}

app/views/admin/users/index.html.haml
.panel.panel-default
  %table.table 
    %tr.info
      %td Пользователь
      %td заходил раз
      %td Был замечен
      %td Создан
      %td Администратор
      %td
    - @users.each do |user|
      %tr
        %td
          =user.email
        %td
          =user.sign_in_count
        %td
          =user.last_sign_in_at
        %td
          =user.created_at
        %td
          =user.admin
        %td
          =link_to 'Удалить', admin_user_path(user), method: :delete, data: { confirm: 'Ты уверен ?'}

app/views/docs/index.html.haml
.container
  .row
    .col-md-8
      .panel.panel-default
        %table.table
          %tr.info
            %td Документы
            %td
          - @docs.each do |doc|
            %tr
              %td 
                = doc.title
              %td 
                .text-right
                  = link_to content_tag('span','',class: 'glyphicon glyphicon-search'), doc.document.url
    =render './layouts/time'  

app/views/docs/new.html.haml
.container
  .row
    .col-md-6
      .panel.panel-success
        .panel-heading
          Создаем документ 
        .panel-body
          = simple_form_for @doc, html: { multipart: true } do |f|
            = f.input :title, label: 'Название'
            = f.input :document, as: :file, label: 'Загружаем pdf'
            = f.button :submit, 'Сохраняем'

app/views/info/index.html.haml
.container
  .row
    .col-md-8
      .panel.panel-default
        %table.table
          %tr.info
            %td Реквизиты
            %td
          %tr
            %td Полное название организации
            %td Товарищество собственников жилья "Гвардейская площадь 10"
          %tr
            %td Краткое название организации
            %td ТСЖ "Гвардейская площадь 10"
          %tr
            %td Фактический адрес
            %td 172800 Тверская область, г. Андреаполь, пл. Гвардейская, д. 10
          %tr
            %td Юридический адрес
            %td 172800 Тверская область, г. Андреаполь, пл. Гвардейская, д. 10
          %tr
            %td ИНН
            %td 6917003243
          %tr
            %td КПП
            %td 691701001
          %tr
            %td ОГРН
            %td 1146913000101
          %tr
            %td ОКПО
            %td 21320683
          %tr
            %td Расчетный счет
            %td № 40703810719150000038 в Тверском РФ АО Россельхозбанк
          %tr
    = render './layouts/time'      
  .row
    .col-md-8
      .panel.panel-default
        %table.table
          %tr.info
            %td Руководство
            %td
            %td
          %tr
            %td Председатель правления ТСЖ
            %td Соловьев Валерий Николаевич
            %td +7-910-530-87-21
          %tr
            %td Заместитель
            %td Юхно Владимир Михайлович
            %td  +7-905-127-60-60
  .row
    .col-md-4
      .panel.panel-default
        %table.table
          %tr.info
            %td Правление ТСЖ
          %tr
            %td Соловьев Валерий Николаевич
          %tr
            %td Олейник Надежда Михайловна
          %tr
            %td Балан Роман Валерьевич
          %tr
            %td Петров Юрий Иванович
          %tr
            %td Юхно Владимир Михайлович
          %tr.info
            %td Ревизионная комиссия
          %tr
            %td Захарова Любовь Георгиевна
          %tr
            %td Андреева Галина Тимофеевна
          %tr
            %td Медведева Галина Николаевна
          %tr.info
            %td Бухгалтер
          %tr
            %td Лапшина Марина Юрьевна

app/views/news/_navbar.html.haml
.alert.alert-danger
  Внимание! Тестовая версия! V1.0
.panel.panel-default
  .bg-primary
    .panel-body
      .text-center
        %h3
          %span.glyphicon.glyphicon-calendar
            Товарищество собственников жилья  'Гвардейская площадь 10'
.navbar.navbar-default
  .navbar-header
    %button{:type => 'button', :class => 'navbar-toggle', :data => {:toggle  => 'collapse', :target => '#menu' }}
      %span.sr-only
        Открыть навигацию
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
  .collapse.navbar-collapse#menu
    %ul.nav.navbar-nav
      %li 
        = link_to content_tag('span',' Новости и обьявления',class: 'glyphicon glyphicon-comment'), news_index_path
      %li 
        = link_to content_tag('span',' Информация о ТСЖ',class: 'glyphicon glyphicon-list-alt'), info_index_path
      %li 
        = link_to content_tag('span', ' Документы и отчетность',class: 'glyphicon glyphicon-folder-open'), docs_path 
    .collapse.navbar-collapse.navbar-right
      %ul.nav.navbar-nav
        %li 
          = link_to 'Войти', news_index_path
        %li 
          = link_to 'Зарегистрироваться', news_index_path

app/views/news/index.html.haml
.container
  .col-md-8
    .alert.alert-info
      %h4
        .text-center
          %strong
            Информация для жильцов
    .panel.panel-default
      - @news.each do |new| 
        %h3.text-center 
          %strong
            = new.title
        %p.text-center
          = new.description 
        %h5.text-right
          = new.date.strftime('%d-%m-%Y')
        %hr
  = render './layouts/time'      

app/views/user_requests/new.html.haml
.container
  .row
    .col-md-6
      .panel.panel-default
        .panel-heading
          Написать председателю
        .panel-body
          = simple_form_for @user_request do |u|
            =u.input :text, as: :text, label: 'Сообщение'
            =u.button :submit, 'Отправить письмо'