config/routes.rb
Rails.application.routes.draw do
  resources :user_requests
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'news#index'
  namespace :admin do
    resources :news
    resources :docs
    resources :user_requests
    resources :users
  end
  resources :news, only: [:index]
  resources :info, only: [:index]
  resources :docs, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  has_attached_file :document,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join('config/dropbox.yml')

  validates_attachment_content_type :document, content_type: [/pdf\Z/]
end

app/models/new.rb
class New < ApplicationRecord
  validates :title, :description,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_requests
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
end

app/models/user_request.rb
class UserRequest < ApplicationRecord
  belongs_to :user
  after_create :send_notification
  private
  def send_notification
    UserRequestMailer.user_request(self.user.email,self.text).deliver_now
  end
end

app/controllers/admin/docs_controller.rb
class Admin::DocsController < Admin::ApplicationController
  before_action :doc_find, only: [:edit, :update, :destroy]
  def index
    @docs=Doc.all
  end
  def new
    @doc=Doc.new
  end
  def create
    Doc.create(doc_params)
    redirect_to admin_docs_path
  end
  def edit
  end
  def update
    @doc.update(doc_params)
    redirect_to admin_docs_path
  end
  def destroy
    @doc.destroy
    redirect_to admin_docs_path
  end
  private
  def doc_params
    params.require(:doc).permit(:title, :document)
  end
  def doc_find
    @doc=Doc.find(params[:id])
  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::ApplicationController
  before_action :new_find, only: [:edit, :update, :destroy]
  def index
    @news=New.all.order(created_at: :desc)
  end
  def edit 
  end
  def update 
    if @new.update(new_params)
      redirect_to admin_news_index_path
    else
      render :edit
    end
  end
  def new
    @new= New.new
  end
  def create
   @new= New.new(new_params)
   if @new.save
      redirect_to admin_news_index_path
   else
     render :new
   end
  end
  def destroy
    @new.destroy
    redirect_to admin_news_index_path
  end
   private
   def new_params
     params.require(:new).permit(:title, :description, :date)
   end
   def new_find
    @new=New.find(params[:id])
   end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users=User.all
  end
  def destroy
    @user=User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def index
    @docs=Doc.all
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end

end

app/controllers/news_controller.rb
class NewsController<ApplicationController
  def index
    @news=New.all.order(created_at: :desc)
  end
end

app/controllers/user_requests_controller.rb
class UserRequestsController < ApplicationController
  before_action :authenticate_user!
  def new
    @user_request=UserRequest.new
  end
  def create
    @user_request=UserRequest.new(user_request_params)
    @user_request.user=current_user
    @user_request.save
    redirect_to news_index_path
  end
  private
  def user_request_params
    params.require(:user_request).permit(:text)
  end
end

app/helpers/admin/user_requests_helper.rb
module Admin::UserRequestsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/user_requests_helper.rb
module UserRequestsHelper
end

app/views/layouts/_footer.html.haml
.footer
  .panel.panel-default
    .bg-success
      .panel-body
        .text-center
          Written by Alexander Solovyev (c) 2017

app/views/layouts/_navbar.html.haml
.alert.alert-danger
  Внимание! Тестовая версия! V1.7.3
.panel.panel-default
  .bg-primary
    .panel-body
      .text-center
        %h3
          %span.glyphicon.glyphicon-calendar
            Товарищество собственников жилья  'Гвардейская площадь 10'
.navbar.navbar-default
  .navbar-header
    %button{:type => 'button', :class => 'navbar-toggle', :data => {:toggle  => 'collapse', :target => '#menu' }}
      %span.sr-only
        Открыть навигацию
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
  .collapse.navbar-collapse#menu
    %ul.nav.navbar-nav
      %li 
        = link_to content_tag('span',' Новости и обьявления',class: 'glyphicon glyphicon-comment'), news_index_path
      %li 
        = link_to content_tag('span',' Информация о ТСЖ',class: 'glyphicon glyphicon-list-alt'), info_index_path
      %li 
        = link_to content_tag('span', ' Документы и отчетность',class: 'glyphicon glyphicon-folder-open'), docs_path 
    .collapse.navbar-collapse.navbar-right
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li
            = link_to current_user.email, destroy_user_session_path, method: :delete
          %li
            = link_to 'Выйти', destroy_user_session_path, method: :delete
          - if current_user.admin 
            %li
              = link_to 'Админка', admin_news_index_path, method: :get
        - else
          %li
            = link_to 'Войти', new_user_session_path
          %li 
            = link_to 'Зарегистрироваться', new_user_registration_path
- if notice.present? or alert.present?
  .alert.alert-danger
    = notice
    = alert

app/views/layouts/_time.html.haml
.col-md-4
  .panel.panel-default
    %table.table
      %tr.success
        %td Режим работы
      %tr
        %td Пн-Пт 19.00-21.00
      %tr
        %td Cб, Вск Выходной
      %tr.success
        %td Телефон
      %tr
        %td +7-910-530-87-21
    = button_to 'Написать председателю', new_user_request_path, method: :get, class: 'btn-danger'

app/views/layouts/admin/_admin_navbar.html.haml
.navbar.navbar-default
  .navbar-header
  %ul.nav.navbar-nav
    %li
      =link_to 'Новости', admin_news_index_path
    %li
      =link_to 'Документы', admin_docs_path
    %li
      =link_to 'Пользователи', admin_users_path
    %li
      =link_to 'Письма пользователей', admin_user_requests_path
  %ul.nav.navbar-right
    %li
      =link_to 'Вернуться на главную', news_index_path

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gvardeyskaya</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class='admin'>
      <%= render './layouts/admin/admin_navbar'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gvardeyskaya</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class='user'>
      <div class='opacity'>
        <%= render './layouts/navbar' %>
        <%= yield %>
        <%= render './layouts/footer' %>
      </div>
    </div>
  </body>
</html>